export const storeProducts = [
  {
    id: 1,
    title: "Strawberry Cake",
    img: "img/strawberry.png",
    price: 400,
    company: "Goldilocks",
    info:
      "Three-layer vanilla chiffon cake filled with strawberry flavors. The whole cake is iced with whipped strawberry cream cheese and topped with sweet strawberry fillings.",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 2,
    title: "Red Velvet Cake",
    img: "img/redvelvet.png",
    price: 720,
    company: "Red Ribbon",
    info:
      "See the difference with our sooo velvety layered cake, in tasteful premium cream cheese frosting, whip cream, and red velvet crumbs on the top and buttom.",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 3,
    title: "Black Forest",
    img: "img/blk-forest.png",
    price: 600,
    company: "Nikon Cakes",
    info:
      "This cakes combines rich chocolate cake layers with fresh cherries, cherry liqueur,and chocolate bark on top, and whipped cream frosting and surrounded with chocolate bark",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "ButterScoth",
    img: "img/butterscoth.png",
    price: 700,
    company: "Goldilocks",
    info:
      "A moist, from-scratch brown sugar cake topped with butterscotch buttercream made with mango flavored gelatin and topped with chocolate! The cake is covered in more butterscotch chips and totally to die for!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Choco Lava",
    img: "img/Choco-lava.png",
    price: 1500,
    company: "Nikon Cakes",
    info:
      "Our cakes has a delicious and unique flavors. It filled with chocolate in the inside and outside.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Pineapple",
    img: "img/Pineapple.png",
    price: 900,
    company: "Mylene's Cakes",
    info:
      "Three-layer pineapple cake filled with pineapple chunk, pineapple syup and whipped cream. Covered with whipped cream and filled with chocolate ganache. topped with chocolate ganache and wihipped cream and fresh cherry filling and chocolate bark on top",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Ice Cream cake",
    img: "img/ice-cream.png",
    price: 3000,
    company: "Banapple",
    info:
      "A cake filled with ice cream with layers of sponge cake or cookie crumble in between. Covered with whipped cream , sprinkles and topped with chocolate bar. ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Almond Cake",
    img: "img/Almond-cake.png",
    price: 2000,
    company: "Contis",
    info:
      "Two-layer almond cake filled with almond flavore, covered with whipped cream and sliced almond and chocolate ganache on top.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Wedding cake",
    img: "img/wedding.png",
    price: 50000,
    company: "Goldilocks",
    info:
      "Three-story iced, huge rich covered with purple tucco, aan elegant cake that suit on your classic occation.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Apple Cake",
    img: "img/Apple-cake.png",
    price: 1000,
    company: "Nikon Cakes",
    info:
      "Asimple apple cake soft and moist with chunks of sweet apples nestled in a tender and buttery rum cake,Sweetest cake you will ever taste",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Cheese Cake",
    img: "img/cheese-cake.png",
    price: 600,
    company: "Nikon Cakes",
    info:
      "Two-layer chiffon cake filled cream cheese, covered with cheese and topped with cheese and strawberies. The sweetest cake you will ever taste",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Kiwi Cake",
    img: "img/Kiwi-Cake.png",
    price: 600,
    company: "Nikon Cakes",
    info:
      "Very high in vitamin C, kiwi fruit is far better eaten raw - cooking it destroys the vitamin content and the green colour. The enzymes it contains makes it good for tenderising meat, but they'll also cause milk to curdle and will prevent gelatine and aspic from setting, so don't attempt kiwi ice cream or jelly.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Durian Cake",
    img: "img/durian-cake.png",
    price: 600,
    company: "Contis",
    info:
      "the king of fruits, takes centrestage in this recipe where fresh durian puree is gently folded with just the right amount of cream before being piped into freshly baked choux puffs. It's a treat that all durian lovers can now make at home!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Fruit Cake",
    img: "img/Fruit-cake.png",
    price: 600,
    company: "Contis",
    info:
      "Fruitcake is a cake made with candied or dried fruit, nuts, and spices, and optionally soaked in spirits. In the United Kingdom, certain rich versions may be iced and decorated. Fruitcakes are typically served in celebration of weddings and Christmas.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Concorde Cake",
    img: "img/fudge.png",
    price: 600,
    company: "Contis",
    info:
      "This crunchy, creamy, luscious, whimsical confection of a cake is a chocoholic's dream, with crisp and chewy meringue layers sandwiched with silky chocolate mousse, all hiding under a shower of chocolate meringue sticks.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "Carrot Cake",
    img: "img/Carrot-Cake.png",
    price: 600,
    company: "Mary Grace",
    info:
      "Carrot cake is cake that contains carrots mixed into the batter. Most modern carrot cake recipes have a white cream cheese frosting.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: "Mango Cake",
    img: "img/mango-cake.png",
    price: 600,
    company: "Mary Grace",
    info:
      "Mango cake or mango chiffon cake, is a Filipino layered chiffon cake infused with ripe sweet Carabao mangoes. It is typically topped with mango cream frosting, fresh mango slices, or pureed mangoes in gulaman or gelatin.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: "Orange Cake",
    img: "img/Orange-cake.png",
    price: 600,
    company: "Cake2Go",
    info:
      "This fluffy Orange Cake made with fresh orange juice and orange zest gives it that perfect amount of orange flavor. The frosting is a combination of sweet cream butter, cream cheese, powdered sugar, and orange zest.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: "Rainbow Cake",
    img: "img/Rainbow-cake.png",
    price: 600,
    company: "Red Ribbon",
    info:
      "This Recipe As the classic children's song says, “Red, Orange, Yellow, Green, Blue, Purple Make the Rainbow Bright.” All the colors of that fabulous rainbow come together in a super-celebratory rainbow layer cake that's perfect for any occasion.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: "Sweet Lemon Cake",
    img: "img/sweet-lemon-cake.png",
    price: 600,
    company: "Purple Oven",
    info:
      "It's sweet with amber and tonka bean; it's balsamic and a little spicy but I mostly ... Sheridan Coffee Liquer. the dry down is sweet woody chocolate-coffee cake like. ... Uomo is the defenition of romance, smells so romantic like la nuit de l'homme",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Straberry Cake",
  img: "img/strawberry.png",
  price: 500,
  company: "Goldilocks",
  info: "The most delicious straberry cake in quezon city",
  inCart: false,
  count: 0,
  total: 0,
};
